{
  "openapi":"3.0.2",
  "info": {
    "title":"API Title",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://github.com/DiegoVictor/gofinances-api/blob/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/transactions": {
      "get": {
        "tags": ["transactions"],
        "responses": {
          "200": {
            "description": "Return transactions and balance",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "balances": {
                      "type": "object",
                      "title": "Balance",
                      "properties": {
                        "income": {
                          "type": "number"
                        },
                        "outcome": {
                          "type": "number"
                        },
                        "total": {
                          "type": "number"
                        }
                      }
                    },
                    "transactions": {
                      "type": "array",
                      "items": {
                        "title": "Transaction",
                        "allOf": [
                          {
                            "$ref": "#/components/schemas/Transaction"
                          },
                          {
                            "properties": {
                              "category": {
                                "$ref": "#/components/schemas/Category"
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                "example": {
                  "transactions": [
                    {
                      "id": "90b2ebc6-3085-451c-9cec-e288d0f83346",
                      "title": "Loan",
                      "type": "income",
                      "value": 1500,
                      "category_id": "e5ebd4bd-0ad2-4b7f-abd3-0e886cbd8c40",
                      "created_at": "2021-08-16T01:06:31.993Z",
                      "updated_at": "2021-08-16T01:06:31.993Z",
                      "category": {
                        "id": "e5ebd4bd-0ad2-4b7f-abd3-0e886cbd8c40",
                        "title": "Others",
                        "created_at": "2021-08-16T01:06:31.974Z",
                        "updated_at": "2021-08-16T01:06:31.974Z"
                      }
                    }
                  ],
                  "balance": {
                    "income": 1500,
                    "outcome": 0,
                    "total": 1500
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["transactions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "Transaction",
                "required": [
                  "title",
                  "type",
                  "value",
                  "category"
                ],
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string"
                  },
                  "value": {
                    "type": "number"
                  },
                  "category": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "title": "Rocketseat Course",
                "value": 100,
                "type": "outcome",
                "category": "Study"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new transaction",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Transaction"
                },
                "example": {
                  "title": "Rocketseat Course",
                  "type": "outcome",
                  "value": 100,
                  "category_id": "03641cb2-49b2-4270-9485-702548045136",
                  "id": "a5ecfbfe-d415-44e7-92db-24f45f197ec4",
                  "created_at": "2021-08-16T01:10:16.341Z",
                  "updated_at": "2021-08-16T01:10:16.341Z"
                }
              }
            }
          },
          "401": {
            "description": "You don't have enough money to this transaction!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "You don't have enough money to this transaction!",
                  "code": 141,
                  "docs": "https://github.com/DiegoVictor/gofinances-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/transactions/{id}": {
      "delete": {
        "tags": ["transactions"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Remove a transaction"
          },
          "404": {
            "description": "Transaction not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Transaction not found",
                  "code": 144,
                  "docs": "https://github.com/DiegoVictor/gofinances-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/transactions/import": {
      "post": {
        "tags": ["transactions"],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Import transactions from file",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "title": "Transaction",
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/Transaction"
                      },
                      {
                        "properties": {
                          "category": {
                            "$ref": "#/components/schemas/Category"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "title": "Loan",
                    "type": "income",
                    "value": 1500,
                    "category_id": "e5ebd4bd-0ad2-4b7f-abd3-0e886cbd8c40",
                    "category": {
                      "id": "e5ebd4bd-0ad2-4b7f-abd3-0e886cbd8c40",
                      "title": "Others",
                      "created_at": "2021-08-16T01:06:31.974Z",
                      "updated_at": "2021-08-16T01:06:31.974Z"
                    },
                    "id": "f9219e75-54fb-467e-b142-5bf7604e7bc4",
                    "created_at": "2021-08-16T01:35:23.282Z",
                    "updated_at": "2021-08-16T01:35:23.282Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Missing file",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Missing file",
                  "code": 140,
                  "docs": "https://github.com/DiegoVictor/gofinances-api#errors-reference"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Transaction": {
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": ["income", "outcome"]
          },
          "value": {
            "type": "number"
          },
          "category_id": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Category": {
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Error": {
        "properties": {
          "status": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    }
  }
}
